apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: registry-cluster
servers: 1
agents: 1
image: rancher/k3s:latest
registries:
  create:
    name: registry.localhost
    host: "0.0.0.0"
    hostPort: "5000"